version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4571:4566-4571'
    environment:
      SERVICES: serverless
      LAMBDA_EXECUTOR: docker
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"